name: mapsengine_v1
version: 0.0.0
description: >
  API client library for mapsengine for use with Streamy RPC framework.
authors:
- Streamy
homepage: https://developers.google.com/maps-engine/
environment:
  sdk: '>=1.0.0'
dependencies:
  browser: any
  args: ">=0.9.0"
  meta: ">=0.8.8"
  fixnum: ">=0.9.0"
  json: ">=0.9.0"
  observe: ">=0.9.1"
  streamy: 
    path: /Users/adam.singer/dart/streamy-dart
  quiver: ">=0.14.0"
